version: '3'

services:
  memory-mcp:
    build: .
    command: tail -f /dev/null  # Keep container running
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - MEMORY_FILE_PATH=/app/data/memory.json
      - MCP_CONFIG_DIR=/app/config
      - MCP_DATA_DIR=/app/data
    restart: unless-stopped